#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D source_image;
layout(set = 0, binding = 1, rgba8) writeonly uniform image2D output_image;

void main() {
    const ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 extent = textureSize(source_image, 0);

    if (pixel.x >= extent.x || pixel.y >= extent.y) {
        return;
    }

    imageStore(output_image, pixel, texelFetch(source_image, pixel, 0));
}
